# Config
home: false  # True : Set home as latest post, False : Set home as an index

# Header
menu:
  Archives: /archives
rss: /atom.xml
background: http://reumia.github.io/hexo-theme-zzoman2015/images/background-zzoman2015.jpg # Header Background Image

# Library
fancybox: true

# Widget
# Widget List : category, tag, archive, recent_posts
widgets:
- tag
- category
- recent_posts

# Google Analytics
ga_id :